version: '3'

services:
  web:
    image: docker-php-apache-web
    container_name: php
    build: ./
    ports:
      - "80:80"
    volumes:
      - "c:/git/:/var/www/html/"
      - "./site.conf:/etc/apache2/sites-available/000-default.conf"
      - "./custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "c:/git/log/apache/:/var/log/apache2/"
