version: '3'

services:
  web:
    image: docker-php-apache-web
    container_name: php
    build: ./
    ports:
      - "8080:80"
    volumes:
      - "c:/git2/:/var/www/html/"
      - "./site.conf:/etc/apache2/sites-available/000-default.conf"
      - "c:/git2/log/apache/:/var/log/apache2/"