version: '3'

services:
  web:
    container_name: php
    build: ./
    ports:
      - "8080:80"
    volumes:
      - "c:/git2/:/var/www/html/"
      - "./site.conf:/etc/apache2/sites-available/000-default.conf"
      - "./custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "c:/git2/log/apache/:/var/log/apache2/"